import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router'
import Link from 'next/link'


export default function Home() {
  
  
  return (
    <>
      <Head>
        <title>Shivam's Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <main className={styles.main}>
          <h2>My Blogs</h2>
          <img src="https://images.pexels.com/photos/262508/pexels-photo-262508.jpeg?cs=srgb&dl=pexels-pixabay-262508.jpg&fm=jpg" className='mt-5' width="500" height="250" alt="" />
      </main>
       <div className={styles.blogSection}>
        <h4>Learn Javascript</h4>
        <p>JavaScript , often abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites</p>
       <Link href={`/BlogPost/javascript`}> <div className="btn btn-success mb-4"   >ReadMore...</div></Link>
        <h4>Learn React</h4>
        <p>JavaScript , often abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites</p>
        <Link href={`/BlogPost/react`}><div className="btn btn-success mb-4"  >ReadMore...</div></Link> 
        <h4>Learn Next</h4>
        <p>JavaScript , often abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites</p>
        <Link href={`/BlogPost/next`}><div className="btn btn-success nb-4" >ReadMore...</div></Link>
       </div>
    </>
  )
}
